//@BaseCode
//MdStart
#if ACCOUNT_ON && ACCESSRULES_ON
namespace QuickTemplate.AspMvc.Models.Access
{
    using System;
    ///
    /// Generated by the generator
    ///
    public partial class AccessRule : VersionModel
    {
        ///
        /// Generated by the generator
        ///
        static AccessRule()
        {
            ClassConstructing();
            ClassConstructed();
        }
        /// <summary>
        /// This method is called before a class is constructed.
        /// </summary>
        /// <remarks>
        /// Use this method to perform any necessary initialization or setup logic before creating an instance of the class.
        /// </remarks>
        /// <seealso cref="ClassName"/>
        static partial void ClassConstructing();
        /// <summary>
        /// This method is called when the class is constructed.
        /// </summary>
        /// <remarks>
        /// This is a partial method, meaning that it can only be implemented in a partial class.
        /// The implementation of this method is optional and should be defined in a partial class of the same name.
        /// </remarks>
        static partial void ClassConstructed();
        ///
        /// Generated by the generator
        ///
        public AccessRule()
        {
            Constructing();
            Constructed();
        }
        /// <summary>
        /// This method is called during the construction of the object.
        /// </summary>
        /// <remarks>
        /// This method is partially implemented and can be overridden in derived classes.
        /// </remarks>
        /// <seealso cref="OtherClass"/>
        /// <returns>void</returns>
        partial void Constructing();
        /// <summary>
        /// This method is called when it is partially implemented in a partial class
        /// and provides an opportunity to perform custom logic and initialization.
        /// </summary>
        /// <remarks>
        /// This method should be implemented in a separate partial class file.
        /// It can be used to initialize any private fields or perform additional setup logic
        /// that is specific to this partial class.
        /// </remarks>
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public Logic.Modules.Access.RuleType Type
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public System.String EntityType
        {
            get;
            set;
        }
        = string.Empty;
        ///
        /// Generated by the generator
        ///
        public System.String? RelationshipEntityType
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public System.String? PropertyName
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public System.String? EntityValue
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public Logic.Modules.Access.AccessType AccessType
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public System.String? AccessValue
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public System.Boolean Creatable
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public System.Boolean Readable
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public System.Boolean Updatable
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public System.Boolean Deletable
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public System.Boolean Viewable
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public System.DateTime CreatedOn
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public System.DateTime? ModifiedOn
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public IdType? IdentityId_CreatedBy
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public IdType? IdentityId_ModifiedBy
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public static AspMvc.Models.Access.AccessRule Create()
        {
            BeforeCreate();
            var result = new AspMvc.Models.Access.AccessRule();
            AfterCreate(result);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static AspMvc.Models.Access.AccessRule Create(object other)
        {
            BeforeCreate(other);
            var result = new AspMvc.Models.Access.AccessRule();
            CommonBase.Extensions.ObjectExtensions.CopyFrom(result, other);
            AfterCreate(result, other);
            return result;
        }
        /// <summary>
        ///    This method is a partial method that is executed before the execution of the 'BeforeCreate' method.
        /// </summary>
        static partial void BeforeCreate();
        /// <summary>
        /// Event that is triggered after creating an instance of the AccessRule class.
        /// </summary>
        /// <param name="instance">The newly created instance of the AccessRule class.</param>
        static partial void AfterCreate(AspMvc.Models.Access.AccessRule instance);
        /// <summary>
        /// This method is called before the creation of an object.
        /// </summary>
        /// <param name="other">The object to be created.</param>
        static partial void BeforeCreate(object other);
        /// <summary>
        /// This method is called after the creation of an AccessRule instance.
        /// </summary>
        /// <param name="instance">The AccessRule instance that was created.</param>
        /// <param name="other">Another object that is related to the creation of the AccessRule instance.</param>
        static partial void AfterCreate(AspMvc.Models.Access.AccessRule instance, object other);
        ///
        /// Generated by the generator
        ///
        public void CopyProperties(AspMvc.Models.Access.AccessRule other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                Type = other.Type;
                EntityType = other.EntityType;
                RelationshipEntityType = other.RelationshipEntityType;
                PropertyName = other.PropertyName;
                EntityValue = other.EntityValue;
                AccessType = other.AccessType;
                AccessValue = other.AccessValue;
                Creatable = other.Creatable;
                Readable = other.Readable;
                Updatable = other.Updatable;
                Deletable = other.Deletable;
                Viewable = other.Viewable;
                Id = other.Id;
#if ROWVERSION_ON
                RowVersion = other.RowVersion;
#endif
#if CREATED_ON
                CreatedOn = other.CreatedOn;
#endif
#if CREATEDBY_ON
                IdentityId_CreatedBy = other.IdentityId_CreatedBy;
#endif
#if MODIFIED_ON
                ModifiedOn = other.ModifiedOn;
#endif
#if MODIFIEDBY_ON
                IdentityId_ModifiedBy = other.IdentityId_ModifiedBy;
#endif
            }
            AfterCopyProperties(other);
        }
        /// <summary>
        /// Performs actions before copying the properties of the provided AccessRule object.
        /// </summary>
        /// <param name="other">The AccessRule object to copy properties from.</param>
        /// <param name="handled">A reference to a boolean variable indicating if the action has been handled.</param>
        /// <remarks>This method is intended to be overriden in derived classes to provide custom actions before copying properties.</remarks>
        partial void BeforeCopyProperties(AspMvc.Models.Access.AccessRule other, ref bool handled);
        /// <summary>
        /// Invoked after copying properties from another AccessRule.
        /// </summary>
        /// <param name="other">The AccessRule object from which properties are copied.</param>
        /// <remarks>
        /// This method is called after the properties of a different AccessRule object have been copied
        /// to the current instance. It allows for additional operations or modifications to be performed
        /// on the current instance.
        /// </remarks>
        partial void AfterCopyProperties(AspMvc.Models.Access.AccessRule other);
        ///
        /// Generated by the generator
        ///
        public override bool Equals(object? obj)
        {
            bool result = false;
            if (obj is Models.Access.AccessRule other)
            {
#if ROWVERSION_ON
                result = IsEqualsWith(RowVersion, other.RowVersion) && Id == other.Id;
#else
                result = Id == other.Id;
#endif
            }
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public override int GetHashCode()
        {
            return HashCode.Combine(Type, EntityType, RelationshipEntityType, PropertyName, EntityValue, AccessType, HashCode.Combine(AccessValue, Creatable, Readable, Updatable, Deletable, Viewable, Id));
        }
    }
}
#endif
//MdEnd

