//@BaseCode
//MdStart
#if ACCOUNT_ON && ACCESSRULES_ON
namespace QuickTemplate.WebApi.Models.Access
{
    using System;
    ///
    /// Generated by the generator
    ///
    public partial class AccessRuleEdit
    {
        ///
        /// Generated by the generator
        ///
        static AccessRuleEdit()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        ///
        /// Generated by the generator
        ///
        public AccessRuleEdit()
        {
            Constructing();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public Logic.Modules.Access.RuleType Type
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public System.String EntityType
        {
            get;
            set;
        }
        = string.Empty;
        ///
        /// Generated by the generator
        ///
        public System.String? RelationshipEntityType
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public System.String? PropertyName
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public System.String? EntityValue
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public Logic.Modules.Access.AccessType AccessType
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public System.String? AccessValue
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public System.Boolean Creatable
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public System.Boolean Readable
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public System.Boolean Updatable
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public System.Boolean Deletable
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public System.Boolean Viewable
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public System.DateTime CreatedOn
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public System.DateTime? ModifiedOn
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public IdType? IdentityId_CreatedBy
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public IdType? IdentityId_ModifiedBy
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public static WebApi.Models.Access.AccessRuleEdit Create()
        {
            BeforeCreate();
            var result = new QuickTemplate.WebApi.Models.Access.AccessRuleEdit();
            AfterCreate(result);
            return result;
        }
        ///
        /// Generated by the generator
        ///
        public static WebApi.Models.Access.AccessRuleEdit Create(object other)
        {
            BeforeCreate(other);
            var result = new WebApi.Models.Access.AccessRuleEdit();
            CommonBase.Extensions.ObjectExtensions.CopyFrom(result, other);
            AfterCreate(result, other);
            return result;
        }
        static partial void BeforeCreate();
        static partial void AfterCreate(WebApi.Models.Access.AccessRuleEdit instance);
        static partial void BeforeCreate(object other);
        static partial void AfterCreate(WebApi.Models.Access.AccessRuleEdit instance, object other);
        ///
        /// Generated by the generator
        ///
        public void CopyProperties(WebApi.Models.Access.AccessRuleEdit other)
        {
            bool handled = false;
            BeforeCopyProperties(other, ref handled);
            if (handled == false)
            {
                Type = other.Type;
                EntityType = other.EntityType;
                RelationshipEntityType = other.RelationshipEntityType;
                PropertyName = other.PropertyName;
                EntityValue = other.EntityValue;
                AccessType = other.AccessType;
                AccessValue = other.AccessValue;
                Creatable = other.Creatable;
                Readable = other.Readable;
                Updatable = other.Updatable;
                Deletable = other.Deletable;
                Viewable = other.Viewable;
                CreatedOn = other.CreatedOn;
                ModifiedOn = other.ModifiedOn;
                IdentityId_CreatedBy = other.IdentityId_CreatedBy;
                IdentityId_ModifiedBy = other.IdentityId_ModifiedBy;
            }
            AfterCopyProperties(other);
        }
        partial void BeforeCopyProperties(WebApi.Models.Access.AccessRuleEdit other, ref bool handled);
        partial void AfterCopyProperties(WebApi.Models.Access.AccessRuleEdit other);
    }
}
#endif
//MdEnd