//@BaseCode
//MdStart
#if ACCOUNT_ON && ACCESSRULES_ON
namespace QuickTemplate.AspMvc.Controllers.Access
{
    using Microsoft.AspNetCore.Mvc;
    using TAccessModel = Logic.Models.Access.AccessRule;
    using TViewModel = AspMvc.Models.Access.AccessRule;
    using TFilterModel = AspMvc.Models.Access.AccessRuleFilter;
    using TAccessContract = Logic.Contracts.Access.IAccessRulesAccess<Logic.Models.Access.AccessRule>;
    ///
    /// Generated by the generator
    ///
    public sealed partial class AccessRulesController : Controllers.FilterGenericController<TAccessModel, TViewModel, TFilterModel, TAccessContract>
    {
        ///
        /// Generated by the generator
        ///
        static AccessRulesController()
        {
            ClassConstructing();
            ClassConstructed();
        }
        static partial void ClassConstructing();
        static partial void ClassConstructed();
        protected override string ControllerName => "AccessRules";
        ///
        /// Generated by the generator
        ///
        public AccessRulesController(Logic.Contracts.Access.IAccessRulesAccess<TAccessModel> other)
        : base(other)
        {
            Constructing();
            Constructed();
        }
        partial void Constructing();
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        protected override TViewModel ToViewModel(TAccessModel accessModel, ActionMode actionMode)
        {
            var handled = false;
            var result = default(TViewModel);
            BeforeToViewModel(accessModel, actionMode, ref result, ref handled);
            if (handled == false || result == null)
            {
                result = TViewModel.Create(accessModel);
            }
            AfterToViewModel(result, actionMode);
            return BeforeView(result, actionMode);
        }
        partial void BeforeToViewModel(TAccessModel accessModel, ActionMode actionMode, ref TViewModel? viewModel, ref bool handled);
        partial void AfterToViewModel(TViewModel viewModel, ActionMode actionMode);
    }
}
#endif
//MdEnd
