//@BaseCode
//MdStart
#if ACCOUNT_ON
namespace QuickTemplate.AspMvc.Models.Account
{
    ///
    /// Generated by the generator
    ///
    public partial class IdentityRoleFilter : Models.View.IFilterModel
    {
        ///
        /// Generated by the generator
        ///
        static IdentityRoleFilter()
        {
            ClassConstructing();
            ClassConstructed();
        }
        /// <summary>
        /// Represents a method that is invoked before the constructor of a class is called.
        /// </summary>
        /// <remarks>
        /// This method is only called during class construction and can be overridden in a partial class.
        /// </remarks>
        /// <returns>Void</returns>
        static partial void ClassConstructing();
        /// <summary>
        ///     This method is called when the class is constructed.
        /// </summary>
        /// <remarks>
        ///     This method is declared as a partial method, which means it must be implemented
        ///     in one of the partial class definitions.
        /// </remarks>
        /// <seealso cref="YourClassName"></seealso>
        static partial void ClassConstructed();
        ///
        /// Generated by the generator
        ///
        public IdentityRoleFilter()
        {
            Constructing();
            Constructed();
        }
        /// <summary>
        /// This method is called during the construction of the object.
        /// </summary>
        /// <remarks>
        /// This is a partial method, which means it can be implemented in other parts of the code.
        /// </remarks>
        partial void Constructing();
        /// <summary>
        /// This method is called when the object is constructed.
        /// </summary>
        /// <remarks>
        /// <para>
        /// This method is a partial method, which means it may or may not be implemented in the partial classes associated with the current class.
        /// </para>
        /// <para>
        /// Any additional logic or initialization required for the object's construction should be implemented in this method.
        /// </para>
        /// </remarks>
        partial void Constructed();
        ///
        /// Generated by the generator
        ///
        public string? Designation
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public string? Description
        {
            get;
            set;
        }
        ///
        /// Generated by the generator
        ///
        public bool HasEntityValue => Designation != null || Description != null;
        private bool show = true;
        ///
        /// Generated by the generator
        ///
        public bool Show => show;
        ///
        /// Generated by the generator
        ///
        public string CreateEntityPredicate()
        {
            var result = new System.Text.StringBuilder();
            if (Designation != null)
            {
                if (result.Length > 0)
                {
                    result.Append(" || ");
                }
                result.Append($"(Designation != null && Designation.Contains(\"{Designation}\"))");
            }
            if (Description != null)
            {
                if (result.Length > 0)
                {
                    result.Append(" || ");
                }
                result.Append($"(Description != null && Description.Contains(\"{Description}\"))");
            }
            return result.ToString();
        }
        ///
        /// Generated by the generator
        ///
        public override string ToString()
        {
            System.Text.StringBuilder sb = new();
            if (string.IsNullOrEmpty(Designation) == false)
            {
                sb.Append($"Designation: {Designation} ");
            }
            if (string.IsNullOrEmpty(Description) == false)
            {
                sb.Append($"Description: {Description} ");
            }
            return sb.ToString();
        }
    }
}
#endif
//MdEnd
